### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by patedip** [limin321/addImg2annData#1]
Hi there!

I used this to work around the image issue once converting the GEF file to seurat readable format but I am still having issues with the proper image showing up. When plotting to check the QC i get the following image and I am not sure what I am doing incorrectly:
![image](https://github.com/limin321/addImg2annData/assets/113726310/ef96361c-b85b-48e7-8842-150633098c67)

**Comment by limin321** [comment]
> Hi there!
> 
> I used this to work around the image issue once converting the GEF file to seurat readable format but I am still having issues with the proper image showing up. When plotting to check the QC i get the following image and I am not sure what I am doing incorrectly: ![image](https://private-user-images.githubusercontent.com/113726310/344791299-ef96361c-b85b-48e7-8842-150633098c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NjY2MjcsIm5iZiI6MTcxOTg2NjMyNywicGF0aCI6Ii8xMTM3MjYzMTAvMzQ0NzkxMjk5LWVmOTYzNjFjLWI4NWItNDhlNy04ODQyLTE1MDYzMzA5OGM2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQyMDM4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTcxZWU2ZWNhYmI0Mzc5NjA4ZWVlMmU1ZjI3ZjQ1NGYyODZlZDI5OTlhZTA2NTk2YjBjMGYyNDUzMDBmNzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gABCaSAYMXVKInNQt2KsNrJxLsYeskb3ht_TgIpV16M)

Hi 

Everything you are doing is correct! The legend shows the data is there just not visualized. The default parameters of SpatialFeaturePlot is set for 10X Visium data. Please try the `pt.size=150`, `stroke=5`... please try different parameters to visualize your heatmap. 

Best,
Limin

**Comment by patedip** [comment]
Hi Limin!

So I have been switching around various parameters but it still does not seem to be rendering the image correctly? This is all being done on the demo mouse brain data. The QC png that is generated turned out just fine though. Do you happen to know the parameters you had tested?

Best,
Dipak

**Comment by limin321** [comment]
> Hi Limin!
> 
> So I have been switching around various parameters but it still does not seem to be rendering the image correctly? This is all being done on the demo mouse brain data. The QC png that is generated turned out just fine though. Do you happen to know the parameters you had tested?
> 
> Best, Dipak

Would you mind share your rds obj, I could try and send you the code. Please share your rds to this email: liminchen@completegenomics.com

Best,
Limin

**Comment by patedip** [comment]
The file is too big to send via email. I used this link to download the demo data: http://116.6.21.110:8090/share/dd965cba-7c1f-40b2-a275-0150890e005f

I utilized the tissue.gef file and converted it to h5ad via stereopy and then used the converted file with the regist.tif with addimg2anndata to generate the RDS file.

Best,
Dipak

**Comment by patedip** [comment]
Hi Limin,

I was able to get it to work! pt.size.dactor = 10k with stroke being .25 was able to help me get the visual. So sorry to take up your time like this. Thanks again for making this package!

Best,
Dipak

**Comment by limin321** [comment]
> Hi Limin,
> 
> I was able to get it to work! pt.size.dactor = 10k with stroke being .25 was able to help me get the visual. So sorry to take up your time like this. Thanks again for making this package!
> 
> Best, Dipak

Hi Dipak,

Glad you made it work. A lot of exploration I guess. That is the learning pass. 
I am going to close this topic.

Best,
Limin
